<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BH3MCQC" failures="1" tests="1" name="Test" time="16.17" errors="0" timestamp="2024-10-16T20:57:51 IST">
  <testcase classname="TestCases.Login_DDT" name="verify_LoginDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at Utilities.DataProviders.getData(DataProviders.java:21)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verify_LoginDDT -->
</testsuite> <!-- Test -->
